#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width 0
bspc config focused_border_color \#F9F9FB
bspc config normal_border_color \#D2D8E0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Kitty desktop='^1' follow=on
bspc rule -a google-chrome-stable desktop='^2' follow=on
bspc rule -a Io.elementary.files desktop='^3' follow=on
bspc rule -a Mailspring desktop='^4' follow=on
bspc rule -a  desktop='^5' follow=on
bspc rule -a gnome-control-center desktop='^6' follow=on
bspc rule -a Blueberry.py desktop='^6' follow=on
bspc rule -a org.gnome.Software desktop='^6' follow=on
bspc rule -a Lxappearance desktop='^6' follow=on

bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

# Autostart
picom &
compton --restore &
$HOME/.config/polybar/launch.sh &
feh --bg-fill /home/r/Descargas/fondo/mountain.jpg &
